### ISSUE TITLE
Handling of Edge Cases and Unexpected Inputs

### ISSUE THREAD

**Issue by John-Doe-TypeB** [John-Doe-TypeB/QOS-Testing#5]
Test how the chatbot handles edge cases such as ambiguous questions, contradictory inputs, or rapid-fire questions. Document any unexpected behavior, crashes, or incorrect responses.

**Comment by abheek-das** [comment]
Tested several edge cases, including rapid-fire questions, contradictory inputs, and ambiguous statements. The chatbot struggled with contradictory inputs, often giving inconsistent responses instead of asking for clarification. It also provided partial answers to ambiguous queries without seeking further details.

**Comment by abheek-das** [comment]
After adjustments, the chatbot now handles most edge cases effectively. Contradictory inputs trigger clarification prompts, and the responses to ambiguous questions are more helpful. Marking this issue as resolved.
